### ISSUE TITLE
Relationship between transprob() and multinomial()?

### ISSUE THREAD

**Issue by choisy** [thinhong/denim#25]
I am understanding correctly if I say that the `transprob()` function is a particular case of the `multinomial()` function? In the same sense that `exponential()` is a particular case of the `gamma()` distribution?

**Comment by thinhong** [comment]
I made the `multinomial()` to solve this problem:
<img src="https://user-images.githubusercontent.com/34956551/161943363-fde21241-ec71-4e2c-a4fe-f9dfdaf205e5.png" width=20% height=20%>

The a and b are defined with `transprob()` and the 0.9 and 0.1 are defined with `multinomial()`. But now we can define it as you pointed out in another issue:
<img src="https://user-images.githubusercontent.com/34956551/161946198-54217dc8-5d3b-4f78-9078-e56a6ec7849c.png" width=30% height=30%>

I also implemented an algorithm so that if we don't define the 0.9 and 0.1 with `multinomial()`
<img src="https://user-images.githubusercontent.com/34956551/161945455-63e10169-c804-46ba-9fa1-7c18e92c1634.png" width=20% height=20%>
I will calculate this case by:
* S -> I: `a*S` move to I
* S -> V: the rest after moving to I which is `S - a*S`, so `(S - a*S)*b` move to V

But now after knowing that we can make what I made so complicated before by:
<img src="https://user-images.githubusercontent.com/34956551/161946198-54217dc8-5d3b-4f78-9078-e56a6ec7849c.png" width=30% height=30%>
I will think carefully whether we still need the `multinomial()` or we can do the entire thing with `transprob()`

**Comment by choisy** [comment]
Yes, please do. I am not necessarily saying that you should get rid off anything here, just trying to understand the logic, which is still not too clear to me at the moment. As for the diagramme, I think you should be careful about the notation as well, see in particular the issue #22.
